[2022-02-09 08:59:51,567] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-09 08:59:51,579] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-09 08:59:51,579] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 08:59:51,580] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-09 08:59:51,580] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 08:59:51,592] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2020-11-01 23:00:00+00:00
[2022-02-09 08:59:51,601] {standard_task_runner.py:52} INFO - Started process 307 to run task
[2022-02-09 08:59:51,608] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yelloTaXi_HW_data_ingestee_gcs_dag', 'bigquery_external_table_task', 'scheduled__2020-11-01T23:00:00+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/yelloTaXi_data_ingestee_gcs_dag.py', '--cfg-path', '/tmp/tmpev__eeq1', '--error-file', '/tmp/tmpdqz5gbv_']
[2022-02-09 08:59:51,609] {standard_task_runner.py:77} INFO - Job 479: Subtask bigquery_external_table_task
[2022-02-09 08:59:51,695] {logging_mixin.py:109} INFO - Running <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [running]> on host cc021fb126ed
[2022-02-09 08:59:51,746] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-09 08:59:51,773] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yelloTaXi_HW_data_ingestee_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T23:00:00+00:00
[2022-02-09 08:59:51,774] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-09 08:59:53,375] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yelloTaXi_HW_data_ingestee_gcs_dag, task_id=bigquery_external_table_task, execution_date=20201101T230000, start_date=20220209T085951, end_date=20220209T085953
[2022-02-09 08:59:53,424] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-09 08:59:53,459] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-09 09:14:54,588] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-09 09:14:54,601] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-09 09:14:54,601] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 09:14:54,601] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-09 09:14:54,601] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 09:14:54,614] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2020-11-01 23:00:00+00:00
[2022-02-09 09:14:54,621] {standard_task_runner.py:52} INFO - Started process 356 to run task
[2022-02-09 09:14:54,628] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yelloTaXi_HW_data_ingestee_gcs_dag', 'bigquery_external_table_task', 'scheduled__2020-11-01T23:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/yelloTaXi_data_ingesteee_gcs_dag.py', '--cfg-path', '/tmp/tmpyobqfzkq', '--error-file', '/tmp/tmpry3e3wu5']
[2022-02-09 09:14:54,630] {standard_task_runner.py:77} INFO - Job 565: Subtask bigquery_external_table_task
[2022-02-09 09:14:54,708] {logging_mixin.py:109} INFO - Running <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-11-01T23:00:00+00:00 [running]> on host 75953ff4f3d5
[2022-02-09 09:14:54,764] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-09 09:14:54,790] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yelloTaXi_HW_data_ingestee_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T23:00:00+00:00
[2022-02-09 09:14:54,792] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-09 09:14:56,328] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yelloTaXi_HW_data_ingestee_gcs_dag, task_id=bigquery_external_table_task, execution_date=20201101T230000, start_date=20220209T091454, end_date=20220209T091456
[2022-02-09 09:14:56,368] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-09 09:14:56,453] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
