[2022-02-09 08:59:25,425] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [queued]>
[2022-02-09 08:59:25,495] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [queued]>
[2022-02-09 08:59:25,496] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 08:59:25,497] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-09 08:59:25,498] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 08:59:25,577] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2020-10-01 23:00:00+00:00
[2022-02-09 08:59:25,604] {standard_task_runner.py:52} INFO - Started process 226 to run task
[2022-02-09 08:59:25,638] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yelloTaXi_HW_data_ingestee_gcs_dag', 'bigquery_external_table_task', 'scheduled__2020-10-01T23:00:00+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/yelloTaXi_data_ingestee_gcs_dag.py', '--cfg-path', '/tmp/tmp626k0l9g', '--error-file', '/tmp/tmppj1kncby']
[2022-02-09 08:59:25,642] {standard_task_runner.py:77} INFO - Job 468: Subtask bigquery_external_table_task
[2022-02-09 08:59:25,830] {logging_mixin.py:109} INFO - Running <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [running]> on host cc021fb126ed
[2022-02-09 08:59:25,974] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-09 08:59:26,047] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yelloTaXi_HW_data_ingestee_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T23:00:00+00:00
[2022-02-09 08:59:26,052] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-09 08:59:27,245] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yelloTaXi_HW_data_ingestee_gcs_dag, task_id=bigquery_external_table_task, execution_date=20201001T230000, start_date=20220209T085925, end_date=20220209T085927
[2022-02-09 08:59:27,305] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-09 08:59:27,355] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-09 09:14:54,621] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [queued]>
[2022-02-09 09:14:54,633] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [queued]>
[2022-02-09 09:14:54,634] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 09:14:54,634] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-09 09:14:54,634] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 09:14:54,648] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2020-10-01 23:00:00+00:00
[2022-02-09 09:14:54,655] {standard_task_runner.py:52} INFO - Started process 357 to run task
[2022-02-09 09:14:54,663] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yelloTaXi_HW_data_ingestee_gcs_dag', 'bigquery_external_table_task', 'scheduled__2020-10-01T23:00:00+00:00', '--job-id', '566', '--raw', '--subdir', 'DAGS_FOLDER/yelloTaXi_data_ingesteee_gcs_dag.py', '--cfg-path', '/tmp/tmpof5t8ije', '--error-file', '/tmp/tmpgwz3_yoi']
[2022-02-09 09:14:54,664] {standard_task_runner.py:77} INFO - Job 566: Subtask bigquery_external_table_task
[2022-02-09 09:14:54,755] {logging_mixin.py:109} INFO - Running <TaskInstance: yelloTaXi_HW_data_ingestee_gcs_dag.bigquery_external_table_task scheduled__2020-10-01T23:00:00+00:00 [running]> on host 75953ff4f3d5
[2022-02-09 09:14:54,809] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-09 09:14:54,832] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yelloTaXi_HW_data_ingestee_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T23:00:00+00:00
[2022-02-09 09:14:54,834] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-09 09:14:55,909] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yelloTaXi_HW_data_ingestee_gcs_dag, task_id=bigquery_external_table_task, execution_date=20201001T230000, start_date=20220209T091454, end_date=20220209T091455
[2022-02-09 09:14:55,962] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-09 09:14:55,998] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
